theme: jekyll-theme-cayman
custom_buttons:
  -
    title: Invite Me
    url: https://discord.com/oauth2/authorize?client_id=433078185555656705&permissions=11264&scope=bot+applications.commands
  -
    title: top.gg
    url: https://top.gg/bot/433078185555656705
  -
    title: Support Server
    url: https://discord.gg/j7qpZdE
  -
    title: Source Code
    url: https://github.com/pfgithub/interpunctbot/
  -
    title: Website
    url: https://interpunct.info/
